### ISSUE TITLE
vpException: cannot read line - max number of points in the CAO model

### ISSUE THREAD

**Issue by arvinkx** [lagadic/visp#1035]
Is there any other documentation for the CAO model type other than: [https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-tracking-mb-generic.html#mb_generic_model](url)?

I'm receiving the exception: Cannot read line!
Exception: Exceed the max number of points in the CAO model.
libc++abi: terminating with uncaught exception of type vpException: cannot read line

The CAO file is likely too large with 405, 911 points and the other file I'm loading is less points but I run into a memory limit issue on iOS. 

I'm looking for documentation to figure out how much the CAO model needs to be simplified and determine what the limitations to work under in regards to CAD model complexity. 

Are there any techniques to loading more complex CAD models other than generating a new simplified version of the CAD model?

**Comment by fspindle** [comment]
Unfortunately, there is no more detailed documentation, but if it could help, in http://visp-doc.inria.fr/download/mbt-model/ we provide the material (.obj, .cao, .xml, .init) and videos to test the tracker on CubeSAT satellite or mmicro object (see model-based tracker [use-case](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-tracking-mb.html#mb_use_case)).

We never worked with a `.cao` file that had more than 1 or 2 hundred points.

The exception  "_Exceed the max number of points in the CAO model_" is thrown by [vpMbTracker](https://github.com/lagadic/visp/blob/master/modules/tracker/mbt/src/vpMbTracker.cpp#L1876). Here the threshold is set to `100 000` points.

The tracker was not designed to deal with so many points. 

In general, the technique consists in starting from a complex model like in .obj, .stl, .step or catia format and to create a `.cao` file by hand by taking only some points to simplify the model as much as possible. As you go along and according to the results, the cao model is then enriched to improve the follow-up.

In 2017, a student developed  a blender-based tool to help `.cao` edition. The tutorial is available [here](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-tracking-mb-CAO-editor.html). I mention this work even if I didn't try it since a couple of years.

Hope it helps
