### ISSUE TITLE
visp-mbt-tracker.cpp demo 

### ISSUE THREAD

**Issue by wangbf** [lagadic/visp#179]
the visp-mbt-tracker.cpp demo
![image](https://cloud.githubusercontent.com/assets/4987522/25732869/9ff57450-3186-11e7-8bbf-e197d5ddd7fc.png)

It is seem has some problem, first, I copy the code into my vs, and 
![image](https://cloud.githubusercontent.com/assets/4987522/25732895/d472f3a6-3186-11e7-834d-8fb8d5fc2fd3.png)

second, the mmicro.wrl file can not load success, I got this error msg: **Catch a ViSP exception: Error [8]:      coin not detected with ViSP, cannot load model**

**Comment by fspindle** [comment]
This is not an issue:

- `vpOpenCVGrabber` is only available with OpenCV < 2.4.8. This class is no more present in the doc http://visp-doc.inria.fr/doxygen/visp-daily/index.html
- Support of VRML cad model files is only available if Coin3D is installed. Since you don't built ViSP with Coin, an exception is thrown.
