### ISSUE TITLE
Encountered an error during the build process for iOS project

### ISSUE THREAD

**Issue by cop663** [lagadic/visp#67]
After reading the official [guide](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-install-iOS.html), I was ready to build the ViSP library in Xcode for iOS project, here are the problems:

1. there is no target of "visp". I can only find "visp_XXX", such as "visp_core", "visp_io", etc.

2. Then I follow [this instruction](http://jaym2503.blogspot.my/2013/01/how-to-make-universal-static-library.html) to create a target named, "visp".

3. After adding the corresponding ".cpp" files to "Compile Sources" and ".h" files to "Copy Files" in Build Phases of "visp", I met the following errors:

build "visp"

![111](https://cloud.githubusercontent.com/assets/2016579/15930289/960577ca-2e84-11e6-99cb-9f91458afb3d.jpg)

build "ALL_BUILD"
![222](https://cloud.githubusercontent.com/assets/2016579/15930292/9c4c9f46-2e84-11e6-90b5-4c9b642605f0.jpg)

Thank you!

**Comment by fspindle** [comment]
The [tutorial](http://visp-doc.inria.fr/doxygen/visp-3.0.0/tutorial-install-iOS.html) is definitively out of date for ViSP 3.x. It needs an update. In the meantime, you will find some hints to proceed without using any 3rd parties:

Configure ViSP turning all 3rd parties, examples, tests... off:

	$ mkdir visp-build-ios; cd visp-build-ios
	$ ccmake ../visp -G Xcode -DCMAKE_INSTALL_PREFIX=./install -DBUILD_SHARED_LIBS=OFF -DUSE_OPENCV=OFF -DUSE_CPP11=OFF -DUSE_DC1394=OFF -DUSE_GSL=OFF -DUSE_JPEG=OFF -DUSE_LAPACK=OFF -DUSE_LIBUSB_1=OFF -DUSE_OPENCV=OFF -DUSE_PCL=OFF -DUSE_PNG=OFF -DUSE_PTHREAD=OFF -DUSE_REALSENSE=OFF -DUSE_X11=OFF -DUSE_XML2=OFF -DUSE_ZBAR=OFF -DUSE_ZLIB=OFF -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_DEMOS=OFF -DBUILD_TUTORIALS=OFF

Check that there is no other 3rparty that is ON, turning all USE_<3rd party>=OFF, and proceed to the generation. Then open the Xcode project:

	$ open VISP.xcodeproj 

Click on ViSP in the left column to make appear configuration panel:
<img width="438" alt="ios-click-visp" src="https://cloud.githubusercontent.com/assets/1412746/15984583/50ccb2a6-2fd1-11e6-8a49-875179b19674.png">

Then select the build settings
<img width="730" alt="ios-click-build-settings" src="https://cloud.githubusercontent.com/assets/1412746/15984584/59b43fec-2fd1-11e6-81f5-37bb0d3d99ed.png">

You have to change for each ``visp_<module>`` target the base SDK to Latest iOS. The following image shows how to do the things for ``visp_core``:
<img width="824" alt="ios-set-ios-sdk" src="https://cloud.githubusercontent.com/assets/1412746/15984616/5249b7ea-2fd2-11e6-980f-6df12d39efa8.png">

Do the same for  ``visp_detection``,  ``visp_gui``... ``visp_tt_mi``.
Now you may select your target (iPhone, iPad...)
<img width="421" alt="ios-set-target-iphone" src="https://cloud.githubusercontent.com/assets/1412746/15984977/d7ce2404-2fdd-11e6-81c6-9cdfc1bfaa57.png">

You are now ready to build ViSP for an iPhone device using the play button
<img width="421" alt="ios-build" src="https://cloud.githubusercontent.com/assets/1412746/15984999/72bbee74-2fde-11e6-9cc9-e157818a230c.png">

To finish the process, proceed to the installation selecting install target before applying play button
<img width="428" alt="ios-install" src="https://cloud.githubusercontent.com/assets/1412746/15985015/98fbca2c-2fdf-11e6-8954-aee42982c9d5.png">

The build SDK containing includes and static libraries is available in ``./visp-build-ios/install``
 
PS: Since I haven't any iOS device under the hand, any feedback is welcome

**Comment by cop663** [comment]
Thank you! fspindle 

There is still one problem after running the target of "install"

![untitled 10](https://cloud.githubusercontent.com/assets/2016579/15985561/806f07ae-3024-11e6-83e4-b8e6d7db778d.jpg)


attached for your reference

Thank you!

**Comment by technommy** [comment]
Got the same problem here, the library was successfully generated without any warning poped up, thanks so much : ) @fspindle

**Comment by fspindle** [comment]
You haven't the rights to install in the default location ``/usr/local``. As given in my previous post, use ``ccmake -DCMAKE_INSTALL_PREFIX=./install ...`` to change the install path

**Comment by fspindle** [comment]
I introduced a more elegant way to generate a ViSP framework for iOS. The tutorial is here http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-install-iOS.html
